name = "rtx-ai-speech-improver"
main = "src/worker.ts"
compatibility_date = "2026-06-05"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[vars]
APP_BASE_PATH = "/apps/speechimprover/"

[[d1_databases]]
binding = "IMPROVER_DB"
database_name = "rtx_ai_speech_improver_db"
database_id = "cf16d76a-38b2-4456-8949-4d85502d4d66"
